### ISSUE TITLE
Windows on minimizing leaving an afterimage [Wayland]

### ISSUE THREAD

**Issue by dashmesh98** [murat-cileli/kwin-grayscale-effect#7]
As you can see in the attached video, on enabling the grayscale effect and trying to minimize the settings app, it is leaving an afterimage.

https://user-images.githubusercontent.com/58769768/221613542-3d2932b9-1cfc-4376-8129-81e2950f134f.mp4

On a side note, it is a much needed effect and I really appreciate the work you have done.

**[ Specifications ]**
Operating System: EndeavourOS 
KDE Plasma Version: 5.27.1
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.12-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by TheAmogh** [comment]
Same here. Thank you so much for this effect!

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-40-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 3 5300U with Radeon Graphics
Memory: 7.1 GiB of RAM
Graphics Processor: RENOIR

**Comment by TheAmogh** [comment]
Adding `effects.windowMinimized.connect(grayscaleEffect.cancelAnimation);` to the init() worked for me!

**Comment by dashmesh98** [comment]
Yeah, this works for me too. Thanks a lot man!!

**Comment by IkelAtomig** [comment]
I still have this on my machine too. Same behaviour. Kind of annoying for a good feature like this.

---

Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.7.3-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland

**Comment by TheAmogh** [comment]
@IkelAtomig You could try the fix above: https://github.com/murat-cileli/kwin-grayscale-effect/pull/8/commits

**Comment by IkelAtomig** [comment]
I tried it today, It worked. Thank you. Forget to comment about it. Hope it get merged by @murat-cileli

**Comment by waleiss** [comment]
Hello, i am using a [fork](https://github.com/skbeh/kwin-grayscale-effect) of this plugin, because this original repo doesn't seem to work in kde 6 (i tried installing the latest version of the original repo and didn't work), only that fork (the guy commited some changes that made it work in kde 6), but unfortunately the fork has this same afterimage problem, and when i add `effects.windowMinimized.connect(grayscaleEffect.cancelAnimation);` to the init() of the fork project the whole plugin stops working, and when i remove this line it starts working again, do any of you guys know to fix this?

Operating System: openSUSE Tumbleweed 20240403
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.8.2-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × 13th Gen Intel® Core™ i5-13450HX
Memory: 15,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3050 6GB Laptop GPU/PCIe/SSE2
